---
- hosts: tomcat
  become: true
  tasks:
    - name: remove existing files
      shell: rm -rf /tmp/hello-world-war-{{ version }}.war
    - name: Install pip3
      apt: 
         name: python3-pip
         state: present
    - name: Install lxml
      pip: 
         name: lxml
    - name: download war file
      maven_artifact:
        group_id: com.efsavage
        artifact_id: hello-world-war
        extension: war
        version: "{{ version }}"
        repository_url: http://54.81.106.225:8081/repository/test-release/
        username: admin
        password: admin123
        dest: "/tmp/hello-world-war-{{ version }}.war"
        mode: '0644'
    - name: copy the war file
      copy:
        src: /tmp/hello-world-war-{{ version }}.war
        dest: /opt/apache-tomcat-9.0.71/webapps
        remote_src: yes
    - name: stop tomcat services
      shell: /opt/apache-tomcat-9.0.71/bin/shutdown.sh
    - name: start tomcat services
      shell: nohup /opt/apache-tomcat-9.0.71/bin/startup.sh
