---
# tasks file for tomcat

- name: Install lxml
  pip: name=lxml

- name: remove war file from temp folder
  shell: rm -rf /tmp/hello-world-war-1.0.0.war

- name: "Download war file"
  maven_artifact:
    group_id: com.efsavage
    artifact_id: hello-world-war
    extension: war
    version: '{{ version }}'
    repository_url: "http://3.110.85.40:8081/repository/hello-release/"
    username: admin
    password: 12345
    dest: "/tmp/hello-world-war-1.0.0.war"
    mode: '0644'

- name: download tomcat server packages
  get_url:
    url: https://dlcdn.apache.org/tomcat/tomcat-10/v10.0.27/bin/apache-tomcat-10.0.27.tar.gz
    dest: /usr/local

- name: extract tomcat packages
  unarchive:
    src: /usr/local/apache-tomcat-10.0.27.tar.gz
    dest: /usr/local
    remote_src: yes

- name: Copy the war file
  copy:
    src: /tmp/hello-world-war-1.0.0.war
    dest: /usr/local/apache-tomcat-10.0.27/webapps/
    remote_src: yes

- name: changing tomcat port number
  template:
    src: /var/lib/jenkins/workspace/AnsibleDemo/server.xml.j2
    dest: /usr/local/apache-tomcat-10.0.27/conf/server.xml
    mode: '0777'
    
  notify: restart tomcat
  
